services:
  jenkins-master:
    #image: jenkins-master
    build:
        context: ./jenkins-master
        dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-master 
    ports:
      - "50000:50000"
      - "8443:8443"
    volumes:
      - jenkins_https_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - adventuretube-jenkins-network
  jenkins-agent:
    # image: striderlee/jenkins-agent
    build:
       context: ./jenkins-agent
       dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-agent
    expose:
      - 22
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_agent_home:/home/jenkins
    networks:
      - adventuretube-jenkins-network
    environment:
      - JENKINS_URL=http://jenkins-master:8443 
      - JENKINS_AGENT_NAME=ssh-agent
      # just remember PRIVATE KEY will need extra carrage-return at the end of context once it uploaded to git hub .. Dont know why 
      # So added carrage-return and did ulpoad to git again and seems like working now but need to check in every fresh installation process
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQKSl9plz2uFm1r98ZOxUh2rAdU9QX2u8tR5zlO1D+XWM5jhl6KShmQVDCUdKzh8PVGf9/qAFLKsyZ+rPjjSu0d2dIY0tzOllW0StsHvREKAPgZE3GxczozbSfONz0qTK8oWwQ+Qr7FABFO6WZE8Y2dAb5guKgF3Ee1bucXTKYJLrsu45qT5cZQ7fGnZCZ6fjUrkPNmUF4Z5owvqokCcnzsDwleoVivDtxyq8Eb6KO+hKQp/IMHzHVW5teTbQiUQj1V0mbclgmMJoZbF7cY8UnTI8p7kXBZvBXe3+DW5Cypqj6+xtcWLfzIEubHrkwveBmpPk45eRMFtBSUwXHf7oCYIuwqjz6p7i0BRXEFbaEJ7U5TSEfeYBfgRliO+v3U4HPe+3yViE+MSqr3cUqvop0qaakHxM6R6TuTK2zzSOaCEZqcv1MKQLarzo8aE7E3pRG9QgKgqRo3A68/HucmdQtDTxJ+5UxABAeeEwZGN29W+54HPhGw/JrRjg6II/6T88= chrislee@localhost
     

                                 


volumes:
  jenkins_https_home:
  jenkins_agent_home:

networks:
  adventuretube-jenkins-network:
    driver: bridge
    name : adventure-jenkins-network





