version: '3.8'
services:
  jenkins-master:
    image: jenkins-master
    # build:
    #     context: ./
    #     dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
      - "8443:8443"
    volumes:
      - jenkins_https_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
  jenkins-agent:
    image: striderlee/jenkins-agent
    # build:
    #    context: ./
    #    dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-agent
    expose:
      - 22
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_URL=https://strider.freeddns.org:8443
      - JENKINS_AGENT_NAME=ssh-agent
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD1r85wNuHugx4rCAx/YJlhw96h4TeCBUwtA3gXis9cm4d9Wi2dn6PMveDKM5Qi0P9f6hZEWhyla3FTv3oeqctI0nL7aD4BlsM9W6qRtcjUaYr+3Q8Q7tEJx3ZH9wq9CirYkh2L4dv6hn3TRDbxKEfTLhti8wUoM7hxDo5AxE9rrmHgctBFQV83XmCAc5HCNBLhNXyl/HU/4G68H0BtdKS3MStGtRnoyQRN6c0cg6Z014BDLdDshzvJWyGt1Ce7ne3uxLFB8CzbfF7tbmWq8wZNRQAnTLS4Ga2FuC8r5h/8/GD8vQ0/ujoA9RNjzNJWJslc+bQjK/9i6KP+GQDKLj4RKi6sEzxacb1IWLtP3yYgXzY52i1ZJXzTWp8C1TTF0Qv74eR9O4+J9VmQHDtACvSFjp/28DD4Jti+c2UabcWxZnZRLNJ2i/DGkhxhV8V5a17hO9FkCtdk8WvbBhvr0s/qCig+pbyzsLe377CdedgSWgM0R1nZbvaAkS2Y/WvaTI0= strider@strider-jenkins
volumes:
  jenkins_https_home:

networks:
  jenkins-network:



