version: '3.8'
services:
  jenkins-master:
    image: jenkins-master
    privileged: true
    user: root
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--httpPort=-1 --httpsPort=8443" # Configure HTTPS
      - JENKINS_HTTPS_KEYSTORE=/var/jenkins_home/keystore.jks # Path to your keystore file
      - JENKINS_HTTPS_KEYSTORE_PASSWORD=5785ch00 # Keystore password
    networks:
      - jenkins-network
  jenkins-agent:
    image: jenkins-agent
    privileged: true
    user: root
    container_name: jenkins-agent
    expose:
      - 22
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_URL=http://strider.freeddns.org:8080
      - JENKINS_AGENT_NAME=ssh-agent
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCPSEozggv6/FWeZqkDJ8UyWKiD7/6+LLMcYUkqpMiTQs2q74KC3L9mSnqw/G7jvfBhR6TZqxytgtqzVFPVEWMLLTWjNRNltOhCXNkDr+RLv0ihyPqhV3KDhuIIXZQsHEX15mBQjLnE8hfcWEJMD79SmAM0noJ7X5R91skcfm3sruPaHWNhOUoOnTVE5yRdnFha18GaLkUAB7XNFVk0L5J40ME9dngYcTApMp5UgYmvyLMKOKNS1rrMQJTSDjhHUW2YLTEzdjWMgXpcqQnlzCrqn/cUnolcgePQgV3CRSRcD5BV/bNUjhe9hH1K3010CdjdTzZ+ooysDOO/+nLSrLrgYV2s8JA/yPlU/s+mDA3mAZ14kP4I1GEaVDoXrm/Z7NMJ34MkPzNbaX4OUJXqIwYrphBqFQ27PoOpTKScNBk48HDBvNV1+zVuEmBBOz0OpJSzgkcjcxWh4rIdnTufxEHCPL/ys9H9nLhWg9dNp2h2wgLtS1Pi1n8OEYYt7X1ss1E= Jenkins agent key
volumes:
  jenkins_home:

networks:
  jenkins-network:



