version: '3.8'
services:
  jenkins-master:
    #image: jenkins-master
    build:
        context: ./jenkins-master
        dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-master
    ports:
      - "50000:50000"
      - "8443:8443"
    volumes:
      - jenkins_https_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
  jenkins-agent:
    image: striderlee/jenkins-agent
    # build:
    #    context: ./jenkins-agent
    #    dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins-agent
    expose:
      - 22
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_URL=https://strider.freeddns.org:8443
      - JENKINS_AGENT_NAME=ssh-agent
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjJwoBkyEIIrN0V4kXuZ3Hfo3HWup7Lu6194J+Xbd77thewSFQUv4GD4jWmK3dTDp0/jQKKimC/iPYVmrFRx5V20sssWinp6RAduz4w2k+fuduPbAaq0r5rbtHPxusoxDM2M7FUTVDF310R99AU0pkxac4Q7UY72lzYaOw6Jrljy232cQaVIPIT3jDr+8SJrNDIDm+Iph7JUV2RzFzXzU/+EZNa02FZgqEtqSh5O+7JpDeX2xCuEZ5Glq7lLuZ7EFaEVv45m7/dA2eIqsVPQltZ580ck+ayILETHX2yccJuCsYyL3IysSd+TxftAAoJdAB6HgZSijjb1m3PWlUE8J3FIDJCvaxNs5uh0ebh1TXeGQGA1rOW6+GWB5ypbPhSCTlBkakbrbhqY7+1sMmwzyvctEC4Xv2z81ZF1rYZHAhuf7RK4AN9wxdER8BiJFhIWmmBKomyLNnu9euHf47chemIIKiC/mJPnrWgBu8srb678y3ThNaMLp+T6S38bUYfaE= jenkins@2f6eae8d9871


volumes:
  jenkins_https_home:

networks:
  jenkins-network:



